DDS-872-eventual_consistency_status
Duke-Translational-Bioinformatics/duke-data-service pull request #1024
Opened 2017-06-12 15:31 UTC by dmlond

attempt to push smaller commits for review
more to come

2017-06-13 19:03 UTC, dmlond commented
ready for official review :)

2017-06-14 19:11 UTC, dmann requested changes
Just a couple changes, nothing major though.

2017-06-14 19:11 UTC, dmann commented on app/jobs/project_storage_provider_initialization_job.rb
> +    project.update(is_consistent: true)
Should handle a failed update here. Maybe call `update!` instead, which will throw an exception if a validation error occurs.

2017-06-14 19:11 UTC, dmann commented on app/models/upload.rb
> +  def make_consistent
Would it be possible to have a more descriptive name for this method? `make_consistent` is kind of vague IMHO.

2017-06-14 19:11 UTC, dmann commented on app/models/upload.rb
> +      update_attributes({
`update_attributes` is an alias for `update`[1] and will run all the validations and whatnot on the object. I'm not sure what will happen here in the case of a validation failure.

1. http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attributes

2017-06-14 19:11 UTC, dmann commented on app/models/upload.rb
>      update_attributes({
Possibly another case for `update!`

2017-06-14 19:11 UTC, dmann commented on app/serializers/upload_serializer.rb
> +      has_integrity_exception: object.has_integrity_exception?,
We have a couple issues here. First, the attribute `has_integrity_exception` isn't actually set anywhere, so this will always return `false`. That's fine, because I don't think that we actually need that attribute. The integrity of the upload can be inferred from the presence of the `error_message`, which is set when an integrity exception is raised.

If uploads start using `error_message` for non-integrity related exceptions, I suggest we add a `error_type` attribute.

2017-06-15 12:54 UTC, dmlond commented on app/models/upload.rb
> +  def make_consistent
ARGH! vcr! :{

2017-06-16 18:06 UTC, dmann approved these changes

2017-06-16 19:06 UTC, merged