Rails ERD Changes. Builds model diagram
Duke-Translational-Bioinformatics/duke-data-service pull request #1033
Opened 2017-07-13 15:42 UTC by bchaballout

This is how you run to build the model diagrams: `docker-compose run bundle exec erd`

More information about Rails ERD available here:
http://voormedia.github.io/rails-erd/install.html

2017-07-13 16:20 UTC, dmann requested changes

2017-07-13 16:20 UTC, dmann commented on Gemfile
> +group :development do
change this to group :docker
--dmlond

2017-07-13 16:20 UTC, dmann commented on docker-compose.dev.yml
> +    links:
We should create a new application entry using `bundle` as an example, changing the name and entry point to `erd`. This should allow us to call `docker-compose run erd` without having to use `bundle exec`.

2017-07-17 14:08 UTC, dmlond approved these changes
looks great!

2017-08-16 19:02 UTC, dmann approved these changes

2017-08-16 19:25 UTC, merged