Dds 922 optimize child deletion job
Duke-Translational-Bioinformatics/duke-data-service pull request #1041
Opened 2017-07-31 20:29 UTC by dmlond

not ready for review yet

2017-08-01 17:58 UTC, dmlond commented
the commit message for [c7350a3](https://github.com/Duke-Translational-Bioinformatics/duke-data-service/pull/1041/commits/c7350a32556b4e6e4d5b5407848f7326ddd2d709) should read child_minder now implements #delete_children instead of #child_deletion.  The method is actually #delete_children

2017-08-01 19:46 UTC, dmann requested changes

2017-08-01 19:46 UTC, dmann commented on spec/support/concerns/child_minder_shared_examples.rb
> +  describe '#paginated_children' do
Since you're only using it within ChildMinder, I think you could probably make #paginated_children a private method and then you wouldn't have to test it directly.

2017-08-10 19:05 UTC, dmann approved these changes

2017-08-10 19:44 UTC, merged