updated to contain proposed endpoints based on GCB feedback
Duke-Translational-Bioinformatics/duke-data-service pull request #1134
Opened 2018-02-14 16:04 UTC by dmlond

2018-02-14 16:22 UTC, dmann requested changes
Two changes, the rest looks good. 👍

2018-02-14 16:22 UTC, dmann commented on api_design/DDS-1061-optimized_directory_structure_endpoint.md
> +| `GET /folders/:id/files` | Get list of files in a folder. |
Let's focus on `GET /projects/:id/files` and lose the `GET /folders/:id/files` for now.

2018-02-14 16:22 UTC, dmann commented on api_design/DDS-1061-optimized_directory_structure_endpoint.md
> +`GET /projects/{id}/files` / `GET /folders/{id}/files`
Please remove '/ `GET /folders/{id}/files`

2018-02-14 20:20 UTC, Donmurry approved these changes
👍

2018-02-15 16:11 UTC, dmlond commented
removed references to `GET /folders/:id/files`

2018-02-15 16:52 UTC, dmann approved these changes

2018-02-15 16:53 UTC, merged