Dds 738 serialize project creator parent
Duke-Translational-Bioinformatics/duke-data-service pull request #853
Opened 2016-12-08 18:11 UTC by dmlond

2016-12-08 21:46 UTC, dmann requested changes
Some changes and a few questions. Good work over all!

2016-12-08 21:46 UTC, dmann commented on app/models/folder.rb
> +    Search::FolderSerializer.new(self).as_json
Namespacing FTW! 👍

2016-12-08 21:46 UTC, dmann commented on app/models/data_file.rb
> +    current_file_version.audits.find_by(action: "create").user
Might want to put a guard clause around this in case current_file_version, .audits, or .find_by(action: "create") return nil.

2016-12-08 21:46 UTC, dmann commented on app/models/folder.rb
> +    audits.find_by(action: "create").user
A guard clause would be good incase audits.find_by returns nil. Though, maybe it'll throw a Record Not Found exception, which could be better/worse?  :\

2016-12-08 21:46 UTC, dmann commented on app/serializers/search/data_file_serializer.rb
> +  def meta
Could the `meta` method possibly work as a has_many? Not a criticism, I'm honestly curious.

2016-12-08 21:46 UTC, dmann commented on circle.yml
> +    - "[[ -z ${RECREATE_SEARCH_MAPPINGS} ]] || heroku run --exit-code rake elasticsearch:index:index_documents  --app 'dukeds-dev'"
Future us should create a single rake task to wrap the 3 elasticsearch tasks needed for recreating search mappings.

2016-12-08 21:46 UTC, dmann commented on spec/models/data_file_spec.rb
> +      expect(subject.current_file_version.audits.find_by(action: 'create')).not_to be_nil
These 3 expectations (lines 257-9) could be broken out into their own contexts, which will ultimately test the guard clause in your creator method.

2016-12-08 21:46 UTC, dmann commented on spec/models/folder_spec.rb
> +  describe 'creator' do
Change to `describe '#creator' do`, we should try to follow the naming convention at http://betterspecs.org/#describe
So, `#` for instance methods and `::` for class methods. (I'm moving away from using the `.` as I've found that it's not explicit enough)

2016-12-08 21:46 UTC, dmann commented on spec/models/folder_spec.rb
> +      expect(subject.audits.find_by(action: 'create')).not_to be_nil
See the above comment regarding contexts and guard clauses.

2016-12-08 21:58 UTC, dmlond commented on app/serializers/search/data_file_serializer.rb
> +  def meta
I dont know? It certainly doesnt lend itself to it. It wants a meta hash, with a series of key (meta_template.template.name): Hash with series of key (meta_property.property.key): meta_property.value entries. These do not align nicely with the underlying object structures

2016-12-08 21:58 UTC, dmlond commented on circle.yml
> +    - "[[ -z ${RECREATE_SEARCH_MAPPINGS} ]] || heroku run --exit-code rake elasticsearch:index:index_documents  --app 'dukeds-dev'"
good idea

2016-12-08 21:59 UTC, dmlond commented on spec/models/folder_spec.rb
> +  describe 'creator' do
thanks. will do this

2016-12-09 17:06 UTC, dmlond commented on app/models/folder.rb
> +    audits.find_by(action: "create").user
👍

2016-12-09 17:06 UTC, dmlond commented on app/models/data_file.rb
> +    current_file_version.audits.find_by(action: "create").user
👍

2016-12-09 17:06 UTC, dmlond commented on spec/models/data_file_spec.rb
> +      expect(subject.current_file_version.audits.find_by(action: 'create')).not_to be_nil
👍

2016-12-09 17:06 UTC, dmlond commented on spec/models/folder_spec.rb
> +  describe 'creator' do
👍

2016-12-09 17:07 UTC, dmlond commented on spec/models/folder_spec.rb
> +      expect(subject.audits.find_by(action: 'create')).not_to be_nil
👍

2016-12-12 19:43 UTC, dmann approved these changes

2016-12-12 19:43 UTC, merged