DDS-800_recursive_deletes
Duke-Translational-Bioinformatics/duke-data-service pull request #943
Opened 2017-02-22 18:33 UTC by dmlond

2017-02-23 16:32 UTC, dmann requested changes
Change FolderDeletionJob to ChildDeletionJob and move perform later to manage_children. Pass in serialized parent object instead of folder_id.

2017-02-24 15:24 UTC, dmlond commented
I made the requested changes. Thanks for the suggestions.

2017-02-27 15:43 UTC, dmann requested changes
I really like what you've done with the ChildMinder module and the ChildDeletionJob. One minor change to the uploads factory to prevent possible test failures.

2017-02-27 15:43 UTC, dmann commented on spec/factories/uploads.rb
> +    name { "#{Faker::Internet.slug}#{rand(10**3)}" }
For uniqueness in a factory attribute, use a sequence:

``
sequence(:name) { |n| "#{Faker::Internet.slug(nil, '_')}_#{n}" }
``

Using rand will still create dups from time to time.

2017-02-27 15:43 UTC, dmann commented on app/jobs/child_deletion_job.rb
> +  queue_as self.name.underscore.gsub('_job','').to_sym
This is a little complex for what amounts to `queue_as :child_deletion`  :\

2017-02-28 14:28 UTC, dmlond commented
ready for review again

2017-02-28 15:02 UTC, dmann requested changes
Sorry that I didn't catch these in my last review. Lesson learned, review all files changed and not just the most recent changes...  :(

2017-02-28 15:02 UTC, dmann commented on Procfile
> +folder_deletion: bundle exec rake workers:delete_folders:run
This should probably be renamed to `child_deletion` and `delete_children`

2017-02-28 15:02 UTC, dmann commented on lib/tasks/workers.rake
> +      workers = [ FolderDeletionJob.job_wrapper ]
I'm surprised that this isn't causing tests to fail, since FolderDeletionJob no longer exists...

2017-02-28 15:02 UTC, dmann commented on spec/lib/tasks/workers_rake_spec.rb
> +    let(:expected_job_class) { FolderDeletionJob }
Are the rake tests running in circle? Because this really should be failing...

2017-02-28 15:05 UTC, dmlond commented on lib/tasks/workers.rake
> +      workers = [ FolderDeletionJob.job_wrapper ]
good catch. These dont run in circle.

2017-02-28 15:14 UTC, dmlond commented
ready for review again

2017-02-28 16:25 UTC, dmann approved these changes
👍

2017-02-28 16:25 UTC, merged